config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'members/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # A Song || Songs
  # Title:
  # Notes:
  # Lyrics:
  # Tempo:
  # Drum Program: 


  root "songs#index"

  get "songs", to: "songs#index", as: "songs" #index_path
  post "songs", to: "songs#create"
  get "songs/new", to: "songs#new", as: "new_song"
  get "songs/:id", to: "songs#show", as: "song" #song_path(:id)
  get "songs/:id/edit", to: "songs#edit", as: "edit_song"
  patch "songs/:id/", to: "songs#update"
  delete "songs/:id", to: "songs#remove"

  resources :members

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
    has_and_belongs_to_many :songs
end

app/models/members_song.rb
class MembersSong < ApplicationRecord
  belongs_to :song
  belongs_to :member
end

app/models/song.rb
class Song < ApplicationRecord
    has_and_belongs_to_many :members
  end
  

app/models/user.rb
class User < ApplicationRecord
    has_one :address, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  def index
    @members = Member.all
  end

  def new
    @member = Member.new
end

  def create
    @member = Member.new(member_params)

    @member.save

    #   # store the data coming from the form into rails session names movies
    #   if session[:songs] == nil
    #     session[:songs] = []
    # end
    # session[:songs].push(params[:song])
    # # redirect to the index html page
    redirect_to members_path
  end

  def member_params
    params.require(:member).permit(:name)
  end
end

app/controllers/songs_controller.rb
# frozen_string_literal: true

class SongsController < ApplicationController
  def index
    @songs = Song.all
      end

  def new
    @song = Song.new
    @members = Member.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def create
    # map the strings in the params[:members] array to the member objects
    new_members = if song_params[:member_ids]
                    song_params[:member_ids].map { |x| Member.find(x) }
                  else
                    []
                   end

    # save the song_params into a variable
    non_members_song_params = song_params

    # remove :members from the new params
    non_members_song_params.delete(:members)

    # create the song
    @song = Song.new(non_members_song_params)

    # create the link of each member to the new song
    new_members.each do |member|
      @song.members << member
    end

    @song.save

    redirect_to songs_path
  end

  def edit
    @song = Song.find(params[:id])
    @members = Member.all
    @song.member_ids = @song.members.all.map(&:id)
  end

  def update
    @song = Song.find(params[:id])

    # map the strings in the params[:members] array to the member objects
    new_members = if song_params[:member_ids]
                    song_params[:member_ids].map { |x| Member.find(x) }
                  else
                    []
                  end
    # save the song_params into a variable
    non_members_song_params = song_params

    # remove :members from the new params
    non_members_song_params.delete(:member_ids)

    # create the link of each member to the new song
    new_members.each do |member|
      @song.members << member unless @song.members.include?(member)
    end
    @song.members.each do |current_member|
      unless new_members.include?(current_member)
        @song.members.delete(current_member)
        end
    end

    @song.update(non_members_song_params)
    redirect_to songs_path
  end

  def remove
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:title, :program, :order, :notes, :lyrics, :tempo, member_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :name, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jammer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/edit.html.erb
<%= form_with model: @member, local: true do |form| %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/members/index.html.erb
<h1>All Members</h1>
<%= link_to 'Songs page', songs_path %>
<%= link_to 'New member', new_member_path %>
<div class = "song-box">
  <% @members.each do |member| %>
    <div class = "song">
      <ul>
        <li class = "Member:"><%= member.name%></li>
        <br>
      </ul>
    </div>
  <%end%>
</div>

app/views/members/new.html.erb
<%= form_with model: @member, local: true do |form| %>


 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/songs/_form.html.erb
<%= form_with model: @song, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :program %><br>
    <%= form.text_area :order %>
  </p>
  <p>
    <%= form.label :notes %><br>
    <%= form.text_area :notes %>
  </p>
  <p>
    <%= form.label :lyrics %><br>
    <%= form.text_area :lyrics %>
  </p>
  <p>
    <%= form.label :tempo %><br>
    <%= form.number_field :tempo %>
  </p>
  <p><% @song.members.each do |member|%>
        <%= member.id %> 
        <%end%>

  </p>
  <p>
      <%= form.label :members %>
      <%=  form.collection_check_boxes :member_ids, @members, :id, :name, include_hidden: false%>
  </p>

  <%# <p> %>
      <%# <%= form.label :members %> 
      <%# <%=  form.collection_check_boxes :members, @members, :id, :name, include_hidden: false %>
  <%# </p> %>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/songs/edit.html.erb
<%= link_to 'Index page', songs_path %>
<%= render 'form' %>

app/views/songs/index.html.erb
<h1>All Songs</h1>
<%= link_to 'Index page', songs_path %>
<%= link_to 'New song', new_song_path %>
<%= link_to 'Members page', members_path %>
<div class = "song-box">
  <% @songs.each do |song| %>
    <div class = "song">
      <ul>
        <li class = "title"><%= song.title%></li>
        <li>Program: <%= song.program%></li>
        <li>Order: <%= song.order%></li>
        <li>Tempo: <%= song.tempo%></li>
        <li>Notes: <%= song.notes%></li>
        <li>Lyrics: <%= song.lyrics%></li>
        <li>Members: <% song.members.each do |member| %>
          <br>
          <%= member.name %>
        <%end%>
        
        </li>
        <%= link_to 'Remove song', song_path(song), method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Edit song', edit_song_path(song) %>
        <%= link_to 'Show song', song_path(song) %>
        <br>
      </ul>
    </div>
  <%end%>
</div>

app/views/songs/new.html.erb
<h1>New page</h1>

<%= link_to 'Index page', songs_path %>
<%= render 'form'%>

app/views/songs/show.html.erb
<h1>Show Song</h1>

<h2>Title: <%= @song["title"]%></h2>
<br>
<p>Program: <%= @song["program"]%></p>
<br>
<p>Order: <%= @song["order"]%></p>
<br>
<p>Tempo: <%= @song["tempo"]%></p>
<br>
<p>Notes: <%= @song["notes"]%></p>
<br>
<p>Lyrics: <%= @song["lyrics"]%></p>
<br>

 <p>Members:<% @song.members.each do |member| %>
 <%= member.name %>, 
<%end%>
</p>
   <%= link_to 'Remove song', song_path(@song), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to 'Edit song', edit_song_path(@song) %>
    <%= link_to 'Index', songs_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>